name: Deployment
description: Deployment issue template
title: "[Deployment]: "
labels: ["deployment", "triage"]
assignees:
  - @dyvenia/devops

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this deployment request!
  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: Specify the deployment environment
      options:
        - label: "Development"
        - label: "Test"
        - label: "Production"
  - type: checkboxes
    id: change-tested
    attributes:
      label: Change Tested
      description: Has the change been thoroughly tested?
      options:
        - label: "locally"
        - label: "In Development environment"
        - label: "In Test environment"
        - label: "Has not been tested"